Repository acm-ucr/isa-website, pull requests merged in 2024-01, with the labels that each got.

#13 added subtitle component
  src/components/handbook/Subtitle.jsx
Labels: ready to review

#16 added name, position props and style
  src/components/board/Board.jsx
  tailwind.config.js
Labels: ready to review, board

#19 Footer Component
  src/app/layout.js
  src/components/Footer.jsx
  src/data/board/Icons.js
Labels: ready to review

#23 Footer Fix
  src/components/Footer.jsx
  src/data/footer/Icons.js
Labels: ready to review

#17 added button component
  src/components/Button.jsx
Labels: do not merge

#28 Made not found page
  src/app/not-found.js
Labels: ready to review, general

#29 Improved "Page Not Found" Text
  src/app/not-found.js
Labels: ready to review, general

#30 new calendar setup
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/events/Calendar.jsx
Labels: events

#32 Worked on title component: text, rectangle & star
  package-lock.json
  src/components/Title.jsx
Labels: ready to review

#33 Social Component
  src/app/page.js
  src/components/home/Icon.jsx
Labels: ready to review

#20 push nav for help
  package-lock.json
  package.json
  src/app/layout.js
  src/components/Navigation.jsx
  src/data/nav.js
Labels: do not merge

#35 added what component
  src/components/home/What.jsx
Labels: ready to review

#24 Added Landing Component
  src/app/page.js
  src/components/home/Landing.jsx
  src/components/home/Splash.jsx
Labels: do not merge

#44 Navbar Responsiveness
  src/components/Navigation.jsx
Labels: ready to review

#47 added Get Involved component
  src/components/Involved.jsx
  src/components/home/Icon.jsx
  src/components/home/Social.jsx
  src/data/home/Socials.js
Labels: ready to review

#57 Mailynnguyen/about page
  src/app/about/page.js
  src/data/about/Sections.js
Labels: do not merge, about

#59 Calendar Styling
  src/components/events/Calendar.jsx
  src/components/events/CustomEvent.jsx
  src/components/events/CustomHeader.jsx
  src/components/events/CustomToolbar.jsx
Labels: do not merge

#25 created values component, needs help with shadows
  src/components/home/Value.jsx
Labels: do not merge

#66 made styling changes to GetInvolved comp
  src/app/page.js
  src/components/home/Social.jsx
Labels: bug, home

#69 made Board page
  src/app/board/page.js
Labels: ready to review, board

#68 Added blue suns
  src/app/about/page.js
  src/components/Footer.jsx
Labels: ready to review

#72 Added calendar modal
  src/components/events/Modal.jsx
Labels: ready to review

#75 Board is now mobile responsive
  src/app/board/page.js
Labels: ready to review, board

#67 About component
  src/app/page.js
  src/components/home/About.jsx
  src/components/home/Landing.jsx
Labels: do not merge

#58 Landing Component Responsiveness
  src/components/home/Landing.jsx
Labels: ready to review

#76 Added Core Values Component
  public/assets/community.svg
  public/assets/gradcap.svg
  public/assets/temple.svg
  src/components/home/Value.jsx
  src/components/home/Values.jsx
  src/data/home/Values.js
Labels: do not merge

#73 Completed the Student Handbook
  src/app/handbook/page.js
  src/components/handbook/Subtitle.jsx
Labels: do not merge

#78 Calendar Page
  src/app/events/page.js
  src/components/events/Calendar.jsx
Labels: ready to review

#79 fix involve section issue
  src/components/Involved.jsx
  src/components/home/Social.jsx
Labels: bug

#92 404 page changes
  src/app/not-found.js
  src/app/page.js
Labels: do not merge

#94 Added Title mobile responsiveness
  src/components/Title.jsx
  src/data/about/Sections.js
Labels: ready to review

#80 completed mobile breakpoints
  src/app/about/page.js
Labels: do not merge
