Repository acm-ucr/isa-website, pull requests merged in 2024-02, with the labels that each got.

#101 make core values section responsive
  src/components/home/Value.jsx
  src/components/home/Values.jsx
Labels: do not merge

#105 adjusted paragraph text size and button text
  src/components/home/What.jsx
Labels: ready to review, home

#96 Added mobile responsiveness to involved component
  src/components/Involved.jsx
  src/components/home/Social.jsx
Labels: ready to review

#106 Removed calendar day transparency
  src/components/events/Calendar.jsx
Labels: ready to review

#113 added sun to board page
  src/app/board/page.js
Labels: do not merge, board

#115 Added stars on What component
  public/assets/stars.svg
  src/components/home/What.jsx
Labels: ready to review

#112 Fixed Navbar UI
  src/components/Navigation.jsx
Labels: bug/ui fix

#120 Added mobile responsiveness to landing component and button
  src/components/Button.jsx
  src/components/home/Landing.jsx
Labels: ready to review

#119 larger footer and animated icons
  src/components/Footer.jsx
  src/data/footer/Icons.js
Labels: bug/ui fix

#118 fixed 404 title size
  src/app/not-found.js
  src/components/Title.jsx
Labels: bug/ui fix

#117 Ssahana05/handbook responsiveness
  src/app/handbook/page.js
  src/components/home/What.jsx
Labels: do not merge

#114 Whatcompmarg
  src/components/home/What.jsx
Labels: do not merge

#135 Mobile Responsiveness: Involved Component
  src/components/home/Involved.jsx
Labels: ready to review

#141 added modal pop-up and ui changes to calendar
  src/app/events/page.js
  src/components/events/Calendar.jsx
  src/components/events/CustomEvent.jsx
  src/components/events/Modal.jsx
Labels: events

#131 Core Values Card - changes regarding sizing made
  src/components/home/Value.jsx
  src/components/home/Values.jsx
Labels: ready to review

#139 Removed excess scrolling for not-found and board page
  src/app/board/page.js
  src/app/layout.js
  src/app/not-found.js
Labels: bug/ui fix, ready to review

#140 Ssant096/landing animation
  src/components/home/Landing.jsx
Labels: ready to review

#146 Mailynnguyen/about page animation
  src/app/about/page.js
Labels: do not merge, about

#147 Added Board Page Animation
  src/app/board/page.js
Labels: do not merge

#150 calendar text lg
  src/components/events/Calendar.jsx
  src/components/events/CustomToolbar.jsx
Labels: bug/ui fix

#148 Custom CSS Calendar
  src/components/events/rbc.css
Labels: do not merge

#152 Rotate Suns
  src/app/board/page.js
  src/app/events/page.js
Labels: ready to review

#155 change core values icons
  src/data/home/Values.js
Labels: do not merge, home

#153 About Margin
  src/components/home/About.jsx
Labels: ready to review

#157 Changes made
  src/app/about/page.js
Labels: bug/ui fix

#161 added social links
  src/components/Navigation.jsx
  src/components/home/Landing.jsx
  src/data/footer/Icons.js
  src/data/home/Socials.js
Labels: ready to review

#159 Calendar Fix
  src/components/events/Calendar.jsx
  tailwind.config.js
Labels: ready to review

#170 Added values animation
  src/components/home/Values.jsx
Labels: bug/ui fix, ready to review

#149 need help with the framer-motion
  src/components/home/About.jsx
Labels: do not merge

#172 Mailynnguyen/delay transition
  src/components/home/Social.jsx
Labels: bug/ui fix

#174 added shadow on hover join
  src/components/Navigation.jsx
Labels: bug/ui fix
