Repository acm-ucr/isa-website, pull requests merged in 2024-03, with the labels that each got.

#177 Handbook animations
  src/app/handbook/page.js
Labels: bug/ui fix

#179 Fixed Landing Mobile Responsiveness
  src/components/home/Landing.jsx
Labels: ready to review

#180 Nav bar responsiveness
  src/components/Navigation.jsx
  src/data/Nav.js
Labels: bug/ui fix, ready to review
